[[session]]
name = "Work ğŸ’¼"
path = "~/Work"

[[session]]
name = "Projects ğŸš€"
path = "~/Projects"
startup_command = "nvim -c ':Telescope find_files'"

[[session]]
name = "Home ğŸ "
path = "~/"
startup_command = "nvim . -c ':Telescope find_files'"

[[session]]
name = "n-vyro ğŸŒ"
path = "~/Work/@n-vyro"

[[session]]
name = "tmux config"
path = "~/.config/tmux"
startup_command = "nvim tmux.conf"

[[session]]
name = "nvim config ğŸ "
path = "~/.config/nvim/"
startup_command = "nvim lua/plugins.lua"

[[session]]
name = "Documents ğŸ“š"
path = "~/Documents"
startup_command = "nvim -c ':Telescope find_files'"

[[session]]
name = "Pictures ğŸ“¸"
path = "~/Pictures"
startup_command = "ranger"
