[default_session]
startup_command = "nvim"

[[session]]
name = "Work ğŸ’¼"
path = "~/Work"

[[session]]
name = "Projects ğŸš€"
path = "~/Projects"

[[session]]
name = "Home ğŸ "
path = "/home/baphled"

[[session]]
name = "n-vyro ğŸŒ"
path = "~/Work/@n-vyro"

[[session]]
name = "tmux config"
path = "~/tmuxfiles/"
startup_command = "nvim tmux.conf"

[[session]]
name = "nvim config ğŸ "
path = "~/.config/nvim/"
startup_command = "nvim lua/baphled/plugins.lua"

[[session]]
name = "Documents ğŸ“š"
path = "~/Documents"

[[session]]
name = "Pictures ğŸ“¸"
path = "~/Pictures"
startup_command = "ranger"

[[session]]
name = "Recipes ğŸ²"
path = "~/vaults/Colledge/3. Resources/Recipes"

[[session]]
name = "baphled Vaults ğŸ—„ï¸"
path = "~/vaults/baphled"

[[session]]
name = "Colledge Vaults ğŸ—„ï¸"
path = "~/vaults/Colledge"

[[session]]
name = "n-vyro.io Vaults ğŸ—„ï¸"
path = "~/vaults/n-vyro.io"

[[session]]
name = "Zettelkasten ğŸ“"
path = "~/vaults/baphled/Zettelkasten"

[[session]]
name = "Dev notes ğŸ“"
path = "~/vaults/baphled/2. Areas/Development"

[[session]]
name = "Remote Session"
path = "~/"
