[[session]]
name = "Home ğŸ "
path = "~/"
windows = [
  "Config âš™ï¸",
  "nvim config ğŸ“",
  "tmux config âš™ï¸",
  "Documents ğŸ“š",
  "Pictures ğŸ“¸"
]
startup_command = "tmux rename-window 'Home ğŸ ' && clear"

[[window]]
name = "Config âš™ï¸"
path = "~/.config"

[[window]]
name = "nvim config ğŸ“"
path = "~/.config/nvim/"
startup_command = "nvim"

[[window]]
name = "tmux config"
path = "~/tmuxfiles/"
startup_command = "nvim"

[[window]]
name = "Documents ğŸ“š"
path = "~/Documents"

[[window]]
name = "Pictures ğŸ“¸"
path = "~/Pictures"
startup_command = "ranger"

# Work

[[session]]
name = "Work ğŸ’¼"
path = "~/Work"
startup_command = "tmux rename-window 'Work ğŸ’¼' && clear"

[[session]]
name = "Projects ğŸš€"
path = "~/Projects"
startup_command = "tmux rename-window 'Projects ğŸš€' && clear"

[[session]]
name = "Remote Session ğŸŒ"
path = "~/"
windows = ["Remote Work", "Remote Projects"]
startup_command = "tmux rename-window 'Remote Session ğŸŒ'"

# Note Taking

[[session]]
name = "Note Taking ğŸ“"
path = "~/vaults/baphled"
windows = ["Colledge Vault", "n-vyro.io Vault", "Boodah", "Book Of YoNix"]
startup_command = "tmux rename-window 'baphled Vault' && clear && nvim"

[[window]]
name = "Colledge  ğŸ“"
path = "~/vaults/Colledge"
startup_command = "nvim"

[[window]]
name = "Boodah  ğŸ“"
path = "~/vaults/Boodah"
startup_command = "nvim"

[[window]]
name = "n-vyro.io ğŸ“"
path = "~/vaults/n-vyro.io"
startup_command = "nvim"

[[window]]
name = "Book Of YoNix ğŸ“"
path = "~/vaults/Book Of YoNix"
startup_command = "nvim"

# n-vyro.io

[[session]]
name = "n-vyro ğŸŒ"
path = "~/Work/@n-vyro/static"
windows = ["build", "core-ruby", "hub", "api", "lib", "bootstrap-ui", "core-components", "esp-ui", "hub-ui"]
startup_command = "tmux rename-window static && clear"

[[window]]
name = "build"
path = "~/Work/@n-vyro/build"
startup_command = "rvm use `cat build/.ruby-version`"

[[window]]
name = "core-ruby"
path = "~/Work/@n-vyro/core-ruby"

[[window]]
name = "hub"
path = "~/Work/@n-vyro/hub"
startup_command = "rvm use `cat hub/.ruby-version`"

[[window]]
name = "api"
path = "~/Work/@n-vyro/api"
startup_command = "rvm use `cat api/.ruby-version`"

[[window]]
name = "lib"
path = "~/Work/@n-vyro/lib"

[[window]]
name = "bootstrap-ui"
path = "~/Work/@n-vyro/bootstrap-ui"

[[window]]
name = "core-components"
path = "~/Work/@n-vyro/core-components"

[[window]]
name = "esp-ui"
path = "~/Work/@n-vyro/esp-ui"

[[window]]
name = "hub-ui"
path = "~/Work/@n-vyro/hub-ui"

[[window]]
name = "static-lib"
path = "~/Work/@n-vyro/static-lib"
