[default_session]
startup_command = "nvim"

[[session]]
name = "Work ğŸ’¼"
path = "~/Work"

[[session]]
name = "Projects ğŸš€"
path = "~/Projects"
startup_command = "nvim -c ':Telescope find_files'"

[[session]]
name = "Home ğŸ "
path = "/home/baphled"
startup_command = "nvim . -c ':Telescope find_files'"

[[session]]
name = "n-vyro ğŸŒ"
path = "~/Work/@n-vyro"

[[session]]
name = "tmux config"
path = "~/tmuxfiles/"
startup_command = "nvim tmux.conf"

[[session]]
name = "nvim config ğŸ "
path = "~/.config/nvim/"
startup_command = "nvim lua/plugins.lua"

[[session]]
name = "Documents ğŸ“š"
path = "~/Documents"
startup_command = "nvim"

[[session]]
name = "Pictures ğŸ“¸"
path = "~/Pictures"
startup_command = "ranger"

[[session]]
name = "Recipes ğŸ²"
path = "~/vaults/baphled/3. Resources/Recipes"
startup_command = "nvim . -c ':Oil'"

[[session]]
name = "baphled Vaults ğŸ—„ï¸"
path = "~/vaults/baphled"
startup_command = "nvim"

[[session]]
name = "n-vyro.io Vaults ğŸ—„ï¸"
path = "~/vaults/n-vyro.io"
startup_command = "nvim"

[[session]]
name = "Zettelkasten ğŸ“"
path = "~/vaults/baphled/Zettelkasten"
startup_command = "nvim"

[[session]]
name = "Dev notes ğŸ“"
path = "~/vaults/baphled/2. Areas/Development"
startup_command = "nvim"

[[session]]
name = "Remote Session"
path = "~/"
